# Generated by Django 5.0.1 on 2024-02-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Разновидность',
                'verbose_name_plural': 'Разновидность',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(max_length=20, verbose_name='Пол')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('location', models.CharField(max_length=255, verbose_name='Место')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('lost', models.BooleanField(default=True, verbose_name='Потерян?')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Добавить фото')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.species', verbose_name='Разновидность')),
            ],
            options={
                'verbose_name': 'Животные',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
