# Generated by Django 5.0.1 on 2024-02-21 19:14

import django.db.models.deletion
import pet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='phone',
            field=models.CharField(max_length=11, validators=[pet.models.validate_phone_number], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pet.lost', verbose_name='Статус'),
        ),
    ]
