# Generated by Django 5.0.1 on 2024-01-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='owner_contact',
            new_name='phone',
        ),
    ]
